---
- name: Remove the installed duo_unix package
  community.general.pacman:
    name: duo_unix
    state: absent
  when: ansible_os_family == 'Archlinux'

- name: Ensure libselinux exists
  ansible.builtin.yum:
    name: "{{ libselinux_package_name }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure SELinux is disabled
  ansible.posix.selinux:
    state: disabled
  when: ansible_os_family == 'RedHat' and ansible_selinux.status == 'enabled'

- name: Ensure needed build packages exists
  ansible.builtin.package:
    name: "{{ duossh_build_packages }}"
    state: present

- name: Get duo_unix archive
  ansible.builtin.get_url:
    url: "https://dl.duosecurity.com/{{ duossh_duosecurity_version }}.tar.gz"
    dest: "/tmp/"
    checksum: "sha256:{{ duossh_duosecurity_checksum }}"
    mode: 0644

- name: Ensure tar is installed
  ansible.builtin.package:
    name: tar
    state: present

- name: Unpack duo_unix archive
  ansible.builtin.unarchive:
    src: "/tmp/{{ duossh_duosecurity_version }}.tar.gz"
    dest: /tmp

- name: Run configure
  ansible.builtin.command:
    chdir: "/tmp/{{ duossh_duosecurity_version }}"
    cmd: "./configure {{ duossh_duosecurity_configure_options | join (' ') }}"
    creates: "/tmp/{{ duossh_duosecurity_version }}/Makefile"
  notify: Install duo_unix

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Create duo config file
  ansible.builtin.template:
    src: etc/duo/pam_duo.conf.j2
    dest: /etc/duo/pam_duo.conf
    owner: root
    group: root
    mode: 0600
