---
- name: Gather os specific variables
  include_vars: "{{ lookup('first_found', items) }}"
  vars:
    items:
      files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      paths:
      - ./vars

- include_tasks: duo.yml

- include_tasks: pam.yml

- include_tasks: ssh.yml
